name: 'ZJU-nCov-Hitcarder Action'

on:
  workflow_dispatch:
  schedule:
    - cron: '2 16 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
            pushplus_token: PUSHPLUS_TOKEN
            pushplus2_token: PUSHPLUS2_TOKEN
          - username: ZJU_USERNAME2
            password: ZJU_PASSWORD2
            pushplus_token: PUSHPLUS_TOKEN
            pushplus2_token: PUSHPLUS2_TOKEN
    steps:
      - name: Working
        uses: chenhy122/zju-ncov-hitcarder@master
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          pushplus_token: ${{ secrets[matrix.pushplus_token] }}
          pushplus2_token: ${{ secrets[matrix.pushplus2_token] }}
